### ISSUE TITLE
Minor misspelling on README

### ISSUE THREAD

**Issue by Rilufi** [privong/pymccorrelation#10]
Hey, just a minor misspelling on the README both here and on the pypi page that could give some trouble in the future, so I thought I could give you a heads up.
On the example to compute the Pearson's r for a sample, using 1000 bootstrapping iterations, you have the formula:
res = pymccorrelation(data['x'], data['y]',
                      coeff='pearsonr',
                      Nboot=1000)

The data for the y variable is typed data['y]' with que quotes off in one side, as it should be data['y'], if copy and pasted directly this simple error can cause some damage until repaired.
That's all, thanks for the package, it really helped me.

**Comment by privong** [comment]
Thanks @Rilufi ! I've fixed the typo. And I'm glad to hear the package has been useful.
